server:
  port: 8082

spring:
  application:
    name: service-store

eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
hystrix:
  command:
    defalt:
      exception:
        isolation:
          thread:
            timeoutInMiliseconds: 40000